name: publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Setup NodeJs 24 💿
        uses: actions/setup-node@v4
        with:
          node-version: 24
          token: ${{ secrets.NPM_TOKEN }}
          registry-url: 'https://registry.npmjs.org'

      - run: yarn --immutable

      - run: yarn build

      - run: |
          npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
